window.addEventListener('hashchange',()=>{if(location.hash==='#admin')navigate('dashboard');else if(location.hash==='#tienda'||!location.hash)renderShop()});
document.getElementById('modal').addEventListener('click',e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal()}});
function registerAgentTools(){const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});const definitions=[{name:'gitanos_read_demo',title:'Consultar la demo de Gitanos',description:'Consulta stock, pedidos y solicitudes ficticias sin modificar datos.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('No se admiten parámetros');return {venues:state.venues.map(v=>({id:v.id,name:v.name,reservedCombos:v.reserve,availableCombos:capacity(v.id)})),orders:state.orders.map(o=>({id:o.id,status:o.status,venue:o.venue})),leads:state.leads.length,events:state.events.length}}},{name:'gitanos_start_replenishment',title:'Preparar reposición de prueba',description:'Abre el formulario de reposición del predio; no crea ni confirma pedidos.',inputSchema:{type:'object',properties:{venueId:{type:'string'}},required:['venueId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input.venueId!=='string'||Object.keys(input).some(k=>k!=='venueId')||!state.venues.some(v=>v.id===input.venueId))throw Error('Predio no válido');if(document.getElementById('modal').open)closeModal();role='admin';navigate('orders');newOrder(input.venueId);return {formOpened:true,venueId:input.venueId,orderCreated:false}}}];for(const def of definitions){try{Promise.resolve(context.registerTool(def,{signal:lifecycle.signal})).catch(()=>{})}catch{}}}
let demoAuthenticated=false;try{demoAuthenticated=sessionStorage.getItem('gitanos-demo-session')==='yes'}catch{}
const renderAdminOrShop=render;
render=function(){if(location.hash.startsWith('#admin')&&!demoAuthenticated){history.replaceState(null,'','#tienda');renderShop();loginDemo();return}renderAdminOrShop()};
function loginDemo(){showModal('Bienvenido a la central.',`<p class="sub" style="margin-bottom:20px">Ingresá para explorar la operación de Gitanos. Usá el acceso de prueba.</p><form id="login-form" class="stack"><label class="field">Email<input name="email" type="email" autocomplete="username" value="prueba1@gimail.com" required></label><label class="field">Contraseña<input name="password" type="password" autocomplete="current-password" placeholder="Ingresá tu contraseña" required></label><label class="field">Explorar como<select name="role" id="login-role"><option value="admin">Administrador · Lucas</option><option value="venue">Cancha / predio</option><option value="supplier">Proveedor</option></select></label><label class="field" id="login-venue" hidden>Predio<select name="venue">${state.venues.map(v=>`<option value="${v.id}">${esc(v.name)}</option>`).join('')}</select></label><label class="field" id="login-supplier" hidden>Proveedor<select name="supplier">${state.suppliers.map(s=>`<option value="${s.id}">${esc(s.name)} · ${s.category}</option>`).join('')}</select></label><div class="notice" style="margin:0">Acceso demo: <strong>prueba1@gimail.com</strong> · clave <strong>1234</strong>.<br>Los datos son ficticios. Este acceso no protege información real.</div><p id="login-error" class="small-text" style="color:var(--red)" role="alert"></p></form>`,`<button class="btn outline" onclick="closeModal()">Volver a la tienda</button><button class="btn primary" type="submit" form="login-form">Ingresar ${icon('arrow',16)}</button>`);document.getElementById('login-role').onchange=e=>{document.getElementById('login-venue').hidden=e.target.value!=='venue';document.getElementById('login-supplier').hidden=e.target.value!=='supplier'};document.getElementById('login-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);if(String(f.get('email')).trim().toLowerCase()!=='prueba1@gimail.com'||f.get('password')!=='1234'){document.getElementById('login-error').textContent='Email o contraseña incorrectos. Usá el acceso de demostración indicado.';return}demoAuthenticated=true;try{sessionStorage.setItem('gitanos-demo-session','yes')}catch{}role=f.get('role');selectedVenue=f.get('venue');selectedSupplier=f.get('supplier');closeModal();navigate('dashboard')}}
function logoutDemo(){demoAuthenticated=false;try{sessionStorage.removeItem('gitanos-demo-session')}catch{}goShop();toast('Sesión de demostración cerrada')}
render();registerAgentTools();
