const PRODUCTS=[
{id:'criollo',name:'El Criollo',short:'Criollo clásico',cat:'chori',category:'Chorizos',price:6900,cost:1100,wholesale:1700,unit:'unidad',tag:'EL DE SIEMPRE, MEJOR',profile:'Puro barrio. Puro fuego.',desc:'Chorizo criollo a la parrilla, chimichurri de la casa y pan crocante. Hay clásicos que no se discuten.',ingredients:'Carne vacuna y de cerdo, ajo, pimienta, orégano y ají molido.',allergens:'Trigo en el pan. Consultar composición final.',weight:'120 g · Pan de 18 cm',image:'criollo',color:'#d3aa72'},
{id:'ahumado',name:'El Ahumado',short:'Ahumado intenso',cat:'chori',category:'Chorizos',price:7900,cost:1350,wholesale:2050,unit:'unidad',tag:'EL FAVORITO DE LA BANDA',profile:'Un poco de humo. Mucha personalidad.',desc:'Pimentón ahumado, ajo y pimienta negra. Intenso, jugoso y con ese sabor que te hace pedir otro.',ingredients:'Carne de cerdo, pimentón ahumado, ajo y pimienta negra.',allergens:'Trigo en el pan. Consultar composición final.',weight:'120 g · Pan de 18 cm',image:'ahumado',color:'#c75f36'},
{id:'mostaza',name:'Mostaza & Miel',short:'Mostaza y miel',cat:'chori',category:'Chorizos',price:8200,cost:1500,wholesale:2250,unit:'unidad',tag:'EL DISTINTO',profile:'Dulce. Picante. Inolvidable.',desc:'Mostaza antigua, un toque de miel y pimienta. El equilibrio justo entre lo dulce y lo parrillero.',ingredients:'Carne de cerdo, mostaza antigua, miel y pimienta.',allergens:'Mostaza y trigo en el pan.',weight:'120 g · Pan de 18 cm',image:'mostaza',color:'#d2a132'},
{id:'provoleta',name:'La Provoleta',short:'Provoleta',cat:'chori',category:'Chorizos',price:8900,cost:1800,wholesale:2650,unit:'unidad',tag:'QUESO, FUEGO Y NADA MÁS',profile:'El que no se comparte.',desc:'Provolone fundido, orégano y un toque ahumado. Toda la magia de la provoleta, adentro de un chori.',ingredients:'Carne de cerdo, provolone, orégano y pimentón ahumado.',allergens:'Leche y trigo en el pan.',weight:'120 g · Pan de 18 cm',image:'provoleta',color:'#c5ae77'},
{id:'roquefort',name:'El Roquefort',short:'Roquefort y pimienta',cat:'chori',category:'Chorizos',price:9200,cost:1900,wholesale:2800,unit:'unidad',tag:'PARA LOS QUE SE ANIMAN',profile:'No pasa desapercibido.',desc:'Queso azul cremoso y pimienta negra. Potente, bien quesero y sin medias tintas.',ingredients:'Carne de cerdo, queso azul y pimienta negra.',allergens:'Leche y trigo en el pan.',weight:'120 g · Pan de 18 cm',image:'roquefort',color:'#8b9f91'},
{id:'rubia',name:'La Rubia',short:'Rubia Golden',cat:'beer',category:'Cerveza',price:4900,cost:750,wholesale:1200,unit:'litro',tag:'FRESCA COMO LA VICTORIA',profile:'Tu compañera de tercer tiempo.',desc:'Golden Ale suave, dorada y refrescante. Servida bien fría, con espuma cremosa y final liviano.',ingredients:'Agua, malta de cebada, lúpulo y levadura.',allergens:'Cebada (gluten). Contiene alcohol.',weight:'Pinta 473 ml · 4,5% alc. · Demo',image:'rubia',color:'#dda731'},
{id:'negra',name:'La Negra',short:'Negra Stout',cat:'beer',category:'Cerveza',price:5400,cost:900,wholesale:1400,unit:'litro',tag:'LA NOCHE EN UNA PINTA',profile:'Oscura. Suave. Con carácter.',desc:'Stout de maltas tostadas, notas de café y cacao y una espuma que se queda hasta el final.',ingredients:'Agua, maltas de cebada tostadas, lúpulo y levadura.',allergens:'Cebada (gluten). Contiene alcohol.',weight:'Pinta 473 ml · 5,2% alc. · Demo',image:'negra',color:'#80664f'}];
const SUPPLIES=[...PRODUCTS,{id:'pan',name:'Pan Gitanos 18 cm',short:'Pan 18 cm',category:'Panadería',wholesale:480,cost:320,unit:'unidad'},{id:'pack',name:'Estuche + servilleta',short:'Packaging',category:'Packaging',wholesale:220,cost:145,unit:'unidad'},{id:'salsa',name:'Salsas · surtido',short:'Salsas',category:'Salsas',wholesale:4200,cost:2800,unit:'kg'}];
const CATEGORIES=['Chorizos','Panadería','Packaging','Cerveza','Salsas'];
const byId=id=>SUPPLIES.find(p=>p.id===id);
function seed(){
const suppliers=[
['s1','Brasa Norte','Chorizos',1,1,98,'24 h','San Martín'],['s2','La Unión Charcutería','Chorizos',0,.94,94,'48 h','Villa Lynch'],['s3','Origen Parrillero','Chorizos',0,1.08,99,'48 h','Munro'],
['s4','Miga de Barrio','Panadería',1,1,97,'Diario','Villa Urquiza'],['s5','Horno 18','Panadería',0,.91,93,'Diario','Saavedra'],['s6','Pan del Sur','Panadería',0,1.06,98,'24 h','Lanús'],
['s7','Cartón Club','Packaging',1,1,99,'72 h','Avellaneda'],['s8','Pack Urbano','Packaging',0,.9,94,'96 h','Quilmes'],['s9','Caja Brava','Packaging',0,1.08,98,'48 h','San Martín'],
['s10','Malta Rebelde','Cerveza',1,1,98,'24 h','Chacarita'],['s11','Birra del Andén','Cerveza',0,.95,95,'48 h','San Isidro'],['s12','Sur Cervecero','Cerveza',0,1.1,99,'24 h','Lanús'],
['s13','Salsas del Patio','Salsas',0,1,91,'48 h','Flores'],['s14','Mesa Criolla','Salsas',0,1.12,97,'48 h','Boedo']
].map(([id,name,category,active,factor,score,lead,zone])=>({id,name,category,active:!!active,factor,score,lead,zone,email:id+'@ejemplo.invalid',status:category==='Salsas'?'Por evaluar':'Homologado'}));
const venues=[{id:'v1',name:'El Poli · Federación Flores',zone:'Flores, CABA',address:'Casimiro Recuero · Flores',manager:'Martín Gómez',email:'poli@ejemplo.invalid',hours:'17:00–00:00',reserve:25,target:120,status:'Operativo',source:'https://www.hoysejuega.com/canchas-de-futbol/88-el-poli-federacion-flores.htm',real:true},{id:'v2',name:'Club La Palmera',zone:'Banfield, Buenos Aires',address:'Banfield · dirección a coordinar',manager:'Sofía Duarte',email:'palmera@ejemplo.invalid',hours:'18:00–01:00',reserve:20,target:100,status:'Operativo',source:'https://canchafija.com.ar/t/club-la-palmera',real:true},{id:'v3',name:'Distrito 5 Fútbol',zone:'Villa Urquiza, CABA',address:'Av. de los Pibes 1250 · ficticia',manager:'Diego Suárez',email:'distrito@ejemplo.invalid',hours:'16:00–00:00',reserve:15,target:90,status:'Operativo',real:false}];
const stock={};venues.forEach((v,vi)=>{stock[v.id]={};SUPPLIES.forEach((p,pi)=>stock[v.id][p.id]=p.id==='pan'?120-vi*30:p.id==='pack'?160-vi*20:p.id==='salsa'?5:p.cat==='beer'?40-vi*10:18+((pi*7+vi*9)%27));});stock.v2.pan=28;
const orders=[];for(let i=0;i<21;i++){const v=venues[i%3];const items=[{id:PRODUCTS[i%5].id,qty:40+(i%4)*10},{id:'pan',qty:60},{id:'pack',qty:60}];if(i%3===0)items.push({id:'rubia',qty:20});const groups=Object.fromEntries([...new Set(items.map(it=>byId(it.id).category))].map(c=>[c,suppliers.find(s=>s.category===c&&s.active)?.id]));orders.push({id:'GT-'+(1027+i),venue:v.id,date:'2026-09-'+String(2+i%18).padStart(2,'0'),slot:'17:00–19:00',status:'Entregado',items:items.map(it=>({...it,price:byId(it.id).wholesale,cost:Math.round(byId(it.id).cost*(suppliers.find(s=>s.id===groups[byId(it.id).category])?.factor||1))})),groups,delivery:Object.fromEntries(Object.values(groups).map(id=>[id,'Entregado'])),note:'Reposición programada',events:[{label:'Pedido recibido',at:'10:30'},{label:'Producción confirmada',at:'11:00'},{label:'Entrega recibida',at:'17:42'}],invoiced:true});}
['En reparto','En producción'].forEach((status,i)=>{const items=[{id:'ahumado',qty:60},{id:'provoleta',qty:30},{id:'pan',qty:90},{id:'pack',qty:90},{id:'rubia',qty:20}].map(it=>({...it,price:byId(it.id).wholesale,cost:byId(it.id).cost}));orders.unshift({id:'GT-'+(1048+i),venue:'v'+(i+1),date:'2026-09-20',slot:i?'18:00–20:00':'17:00–19:00',status,items,groups:{Chorizos:'s1',Panadería:'s4',Packaging:'s7',Cerveza:'s10'},delivery:{s1:status,s4:status,s7:status,s10:status},note:'Reposición del fin de semana',events:[{label:'Pedido recibido',at:'09:00'},{label:status,at:'12:30'}],invoiced:false});});
const invoices=orders.filter(o=>o.invoiced).map((o,i)=>({id:'DEMO-'+String(120+i).padStart(5,'0'),order:o.id,venue:o.venue,total:o.items.reduce((s,it)=>s+it.price*it.qty,0),status:i%5===0?'Pendiente':'Pagada',date:o.date}));
const sales=Array.from({length:16},(_,i)=>({id:'V-'+(501+i),venue:'v'+(i%3+1),channel:i%3?'Local':'PedidosYa demo',product:PRODUCTS[i%7].id,qty:2+i%6,total:(2+i%6)*PRODUCTS[i%7].price,date:'2026-09-'+String(14+i%7).padStart(2,'0'),time:'20:30',status:'Entregado',customer:'Cliente de demostración'}));
return {version:3,suppliers,venues,stock,orders,invoices,sales,leads:[{id:'SOL-1',type:'Cancha',name:'Juan Pérez · La Esquina F5',zone:'Villa Ballester',email:'cancha@ejemplo.invalid',phone:'Contacto demo',message:'Queremos sumar choris de autor y una chopera para el torneo de los viernes.',status:'En evaluación',date:'2026-09-19'},{id:'SOL-2',type:'Proveedor',name:'Lucía · Salsas del Patio',zone:'Flores',email:'salsas@ejemplo.invalid',phone:'Contacto demo',message:'Elaboramos chimichurri y salsa criolla. Nos gustaría presentar muestras para la cata.',status:'Nueva',date:'2026-09-20'},{id:'SOL-3',type:'Consumidor',name:'Nicolás Demo',zone:'Villa Urquiza',email:'nicolas@ejemplo.invalid',phone:'Contacto demo',message:'Quiero enterarme de nuevos sabores y de los eventos de Gitanos.',status:'Nueva',date:'2026-09-20'}],events:[{id:'EV-1',type:'Torneo de fútbol',people:80,date:'2026-10-03',zone:'Flores',package:'Choris + birra',name:'Martín · El Poli',email:'torneo@ejemplo.invalid',message:'Cierre del torneo amateur. Servicio de 20 a 23 h. Caso de demostración.',estimate:1440000,status:'Confirmado'},{id:'EV-2',type:'Evento de empresa',people:45,date:'2026-10-09',zone:'Vicente López',package:'Experiencia completa',name:'Carolina Demo',email:'evento@ejemplo.invalid',message:'Encuentro de equipo al aire libre. Incluir parrilla y chopera.',estimate:1080000,status:'Cotizando'}],equipment:[{id:'EQ-01',type:'Heladera exhibidora',venue:'v1',serial:'GIT-H01',status:'En uso',service:'2026-10-02'},{id:'EQ-02',type:'Parrilla a gas',venue:'v1',serial:'GIT-P01',status:'En uso',service:'2026-10-05'},{id:'EQ-03',type:'Chopera doble',venue:'v2',serial:'GIT-C01',status:'En uso',service:'2026-09-25'},{id:'EQ-04',type:'Heladera exhibidora',venue:'v3',serial:'GIT-H02',status:'En uso',service:'2026-10-10'}],claims:[{id:'RC-021',venue:'v2',order:'GT-1040',type:'Calidad',text:'Se recibieron 8 panes aplastados. Solicita reposición en la próxima entrega.',status:'Abierto',date:'2026-09-20',resolution:''},{id:'RC-020',venue:'v1',order:'GT-1043',type:'Entrega',text:'Reprogramar la ventana de entrega para después de las 18:00.',status:'En revisión',date:'2026-09-19',resolution:''},{id:'RC-019',venue:'v3',order:'GT-1038',type:'Producto faltante',text:'Faltaron 10 estuches en la entrega.',status:'Resuelto',date:'2026-09-18',resolution:'Reposición de 10 estuches recibida.'}],activity:[],cart:{},checkout:null};
}
const STORE='gitanos-demo-v3';let state;try{state=JSON.parse(localStorage.getItem(STORE));if(!state||state.version!==3)state=seed()}catch{state=seed()}
let role='admin',selectedVenue='v1',selectedSupplier='s1',filter='Todos',query='',shopFilter='Todos';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const venueName=id=>state.venues.find(v=>v.id===id)?.name||id;
const supplierName=id=>state.suppliers.find(s=>s.id===id)?.name||'Sin asignar';
const total=o=>o.items.reduce((s,it)=>s+it.qty*it.price,0);
const fmtDate=d=>new Date(d+'T12:00:00').toLocaleDateString('es-AR',{day:'2-digit',month:'short'});
const pill=s=>`<span class="pill ${/producción|Pendiente|revisión|Por evaluar/.test(s)?'orange':/reparto|Nuevo|Confirmado/.test(s)?'blue':/Abierto|Bajo|Rechazado/.test(s)?'red':/Cancelado/.test(s)?'gray':''}">${esc(s)}</span>`;
function save(){try{localStorage.setItem(STORE,JSON.stringify(state));}catch{toast('Tu navegador no permite guardar cambios; se conservarán mientras esta página siga abierta.')}}
function toast(message){const t=document.getElementById('toast');t.textContent=message;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),4500)}
function showModal(title,body,footer=''){const d=document.getElementById('modal');d.innerHTML=`<div class="modal-head"><h2>${title}</h2><button class="icon-button" onclick="closeModal()" aria-label="Cerrar">${icon('close')}</button></div><div class="modal-body">${body}</div>${footer?`<div class="modal-foot">${footer}</div>`:''}`;d.showModal()}
function closeModal(){document.getElementById('modal').close()}
function download(name,text,type='text/csv;charset=utf-8'){const blob=new Blob(['\uFEFF',text],{type});const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)}
const csvCell=s=>'"'+String(s??'').replace(/"/g,'""')+'"';
function exportReport(){const rows=[['Pedido','Predio','Fecha','Estado','Importe ARS'],...state.orders.map(o=>[o.id,venueName(o.venue),o.date,o.status,total(o)])];download('gitanos-pedidos-demo.csv',rows.map(r=>r.map(csvCell).join(';')).join('\r\n'));toast('Reporte de pedidos descargado')}
function activeSupplier(category){return state.suppliers.find(s=>s.category===category&&s.active)}
function orderStatus(o){const statuses=Object.values(o.delivery);return statuses.every(s=>s==='Entregado')?'Entregado':statuses.some(s=>s==='En reparto')?'En reparto':statuses.some(s=>s==='En producción'||s==='Entregado')?'En producción':'Nuevo'}
function createOrder(venue,items,date,slot,note){if(!state.venues.some(v=>v.id===venue))throw Error('Elegí un predio válido.');if(!items.length)throw Error('Agregá al menos un producto.');const groups={};const enriched=items.map(it=>{const p=byId(it.id);if(!p||!Number.isInteger(it.qty)||it.qty<1||it.qty>10000)throw Error('Revisá las cantidades del pedido.');const s=activeSupplier(p.category);if(!s)throw Error('No hay proveedor activo para '+p.category+'. Homologá uno antes de pedir.');groups[p.category]=s.id;return {...it,price:p.wholesale,cost:Math.round(p.cost*s.factor)}});const id='GT-'+(Math.max(...state.orders.map(o=>Number(o.id.slice(3))))+1);const o={id,venue,items:enriched,date,slot,note,status:'Nuevo',groups,delivery:Object.fromEntries(Object.values(groups).map(id=>[id,'Nuevo'])),events:[{label:'Distribuido en las bandejas de '+Object.values(groups).length+' proveedores (demo)',at:'Ahora'}],invoiced:false};state.orders.unshift(o);save();return o}
function advanceOrder(id,supplier){const o=state.orders.find(o=>o.id===id);if(!o||o.status==='Entregado'||o.status==='Cancelado')return;const stages=['Nuevo','En producción','En reparto','Entregado'];const targets=supplier?[supplier]:Object.keys(o.delivery);for(const sid of targets){const prev=o.delivery[sid];if(!prev||prev==='Entregado')continue;const next=stages[stages.indexOf(prev)+1];o.delivery[sid]=next;if(next==='Entregado'){o.items.filter(it=>o.groups[byId(it.id).category]===sid).forEach(it=>state.stock[o.venue][it.id]+=it.qty)}o.events.push({label:supplierName(sid)+': '+next,at:'Ahora'})}o.status=orderStatus(o);if(o.status==='Entregado'&&!o.invoiced){state.invoices.unshift({id:'DEMO-'+String(120+state.invoices.length).padStart(5,'0'),order:o.id,venue:o.venue,total:total(o),status:'Pendiente',date:o.date});o.invoiced=true;}save();render();toast(o.status==='Entregado'?'Entrega registrada: stock actualizado y comprobante generado.':'Estado del pedido actualizado.');}
function capacity(venue){const st=state.stock[venue];return Math.floor(Math.min(PRODUCTS.filter(p=>p.cat==='chori').reduce((s,p)=>s+st[p.id],0),st.pan,st.pack))}
function recordSale(venue,product,qty,channel='Local',extra={}){const p=PRODUCTS.find(p=>p.id===product),v=state.venues.find(v=>v.id===venue);if(!p||!v||!Number.isInteger(qty)||qty<1)throw Error('Revisá el producto y la cantidad.');const st=state.stock[venue];const units=p.cat==='beer'?.473:1;if(st[p.id]+1e-8<qty*units)throw Error('No hay stock suficiente de '+p.name+'.');if(p.cat==='chori'){if(st.pan<qty||st.pack<qty)throw Error('No hay panes o packaging suficientes.');if(channel!=='PedidosYa demo'&&capacity(venue)-qty<v.reserve)throw Error('Esta venta usaría el stock reservado para PedidosYa. Reponé o ajustá la reserva.');st.pan-=qty;st.pack-=qty;}st[p.id]=Math.round((st[p.id]-qty*units)*1000)/1000;const sale={id:'V-'+(501+state.sales.length),venue,product,qty,total:p.price*qty,channel,date:'2026-09-20',time:new Date().toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'}),status:channel==='PedidosYa demo'?'Confirmado':'Entregado',customer:'Cliente demo',...extra};state.sales.unshift(sale);save();return sale}

